# Generated by Django 5.2.15 on 2026-08-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("email_order_updates", models.BooleanField(default=True)),
                ("email_booking_updates", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=False)),
                ("email_marketing", models.BooleanField(default=False)),
                ("profile_visible", models.BooleanField(default=True)),
                ("activity_status", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
    ]
