# Generated by Django 5.2.15 on 2026-08-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_add_booking_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fertilizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "fertilizer_type",
                    models.CharField(
                        choices=[
                            ("Chemical", "Chemical"),
                            ("Organic", "Organic"),
                            ("Fungicide", "Fungicide"),
                            ("Pesticide", "Pesticide"),
                            ("Micronutrient", "Micronutrient"),
                            ("Biofertilizer", "Biofertilizer"),
                        ],
                        default="Chemical",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="fertilizers/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "crops",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated crop names",
                        max_length=300,
                    ),
                ),
                (
                    "prevents",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated diseases/pests it prevents",
                        max_length=300,
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        blank=True, help_text="e.g. 4.0 ml/L", max_length=80
                    ),
                ),
                ("usage_notes", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="per bottle",
                        help_text="e.g. per bottle, per kg, per litre",
                        max_length=30,
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=100)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
