# Generated by Django 5.2.15 on 2026-08-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_add_fertilizer_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="fertilizer",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="External CDN image URL", max_length=500
            ),
        ),
    ]
